import os

from dotenv import load_dotenv


load_dotenv(dotenv_path=".env.test")

AWS_REGION = os.environ.get("AWS_REGION")
SES_SOURCE = os.environ.get("SES_SOURCE")
SES_TARGET = os.environ.get("SES_TARGET")

SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT") or "local"
ENVIRONMENT = os.environ.get("ENVIRONMENT")
LOG_LEVEL = os.environ.get("LOG_LEVEL")
SERVICE_NAME = os.environ.get("SERVICE_NAME")
APP_HOST = os.environ.get("APP_HOST")
APP_PORT = os.environ.get("UVICORN_PORT") or 8003

USERNAME = os.environ.get("USERNAME")
FIRST_NAME = os.environ.get("FIRST_NAME")

CONSUMER_BOOTSTRAP_SERVERS = os.environ.get("CONSUMER_BOOTSTRAP_SERVERS")
CONSUMER_SESSION_TIMEOUT_MILLIS = int(os.environ.get("CONSUMER_SESSION_TIMEOUT_MILLIS"))
CONSUMER_AUTO_OFFSET_RESET = os.environ.get("CONSUMER_AUTO_OFFSET_RESET")
CONSUMER_ENABLE_AUTO_OFFSET_STORE = bool(
    os.environ.get("CONSUMER_ENABLE_AUTO_OFFSET_STORE")
)

QUEUE_PROTOCOL = os.environ.get("QUEUE_PROTOCOL")
QUEUE_HOST = os.environ.get("QUEUE_HOST")
QUEUE_PORTS = os.environ.get("QUEUE_PORTS")
QUEUE_TIMEOUT_SECONDS = int(os.environ.get("QUEUE_TIMEOUT_SECONDS"))
QUEUE_ACKS = os.environ.get("QUEUE_ACKS")
QUEUE_POLL_WAIT_SECONDS = int(os.environ.get("QUEUE_POLL_WAIT_SECONDS"))
QUEUE_TOPIC_NAME = os.environ.get("QUEUE_TOPIC_NAME")
QUEUE_DLQ_NAME = os.environ.get("QUEUE_DLQ_NAME")
QUEUE_GROUP_ID = os.environ.get("QUEUE_GROUP_ID")
EMAIL_VERIFICATION_TYPES = ["CONFIRM_ACCOUNT_VERIFICATION"]

HTTP_STATUS_CODE_EXPIRED_TOKEN = 498
JWT_SECRET_CONFIRM_ACCOUNT = os.environ.get("JWT_SECRET_CONFIRM_ACCOUNT")
JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT = int(
    os.environ.get("JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT")
)

USER_SERVICE_ENDPOINT = os.environ.get("USER_SERVICE_ENDPOINT")
USER_SERVICE_URL = f"{USER_SERVICE_ENDPOINT}/api"
