import os

from dotenv import load_dotenv


load_dotenv()

AWS_REGION = os.environ.get("AWS_REGION")
SES_SOURCE = os.environ.get("SES_SOURCE")

SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT") or "local"
SENTRY_DSN = os.environ.get("SENTRY_DSN")
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE"))
SENTRY_PROFILES_SAMPLE_RATE = float(os.environ.get("SENTRY_PROFILES_SAMPLE_RATE"))
SENTRY_SAMPLE_RATE = int(os.environ.get("SENTRY_SAMPLE_RATE"))

ENVIRONMENT = os.environ.get("ENVIRONMENT")
LOG_LEVEL = os.environ.get("LOG_LEVEL")
SERVICE_NAME = os.environ.get("SERVICE_NAME")
APP_PORT = os.environ.get("UVICORN_PORT") or 8003

CONSUMER_BOOTSTRAP_SERVERS = os.environ.get("CONSUMER_BOOTSTRAP_SERVERS")
CONSUMER_SESSION_TIMEOUT_MILLIS = int(os.environ.get("CONSUMER_SESSION_TIMEOUT_MILLIS"))
CONSUMER_AUTO_OFFSET_RESET = os.environ.get("CONSUMER_AUTO_OFFSET_RESET")
CONSUMER_ENABLE_AUTO_OFFSET_STORE = bool(
    os.environ.get("CONSUMER_ENABLE_AUTO_OFFSET_STORE")
)

QUEUE_PROTOCOL = os.environ.get("QUEUE_PROTOCOL")
QUEUE_HOST = os.environ.get("QUEUE_HOST")
QUEUE_PORTS = os.environ.get("QUEUE_PORTS")
QUEUE_TIMEOUT_SECONDS = int(os.environ.get("QUEUE_TIMEOUT_SECONDS"))
QUEUE_ACKS = os.environ.get("QUEUE_ACKS")
QUEUE_POLL_WAIT_SECONDS = int(os.environ.get("QUEUE_POLL_WAIT_SECONDS"))
QUEUE_TOPIC_NAME = os.environ.get("QUEUE_TOPIC_NAME")
QUEUE_DLQ_NAME = os.environ.get("QUEUE_DLQ_NAME")
QUEUE_GROUP_ID = os.environ.get("QUEUE_GROUP_ID")
EMAIL_VERIFICATION_TYPES = ["CONFIRM_ACCOUNT_VERIFICATION"]
